name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: make
      run: |
      

            sudo apt-get install openjdk-8-jdk
          
            export ANDROID_HOME=~/Android/android-sdk

            export ANDROID_NDK_HOME=~/Android/Sdk/ndk-bundle

            export PATH=$ANDROID_NDK_HOME:$ANDROID_HOME/tools:$PATH

            export PATH=$ANDROID_HOME/build-tools/25.0.2:$PATH

            # Commands:

            sudo apt-get install ant #//If you install manually - set envirnoment value to Ant

            sudo apt-get install make

            sudo apt-get install g++

            sudo apt-get install git-core

             #Download required repos from GitHub (both repos must be downloaded in same folder):

             git clone git://github.com/pelya/commandergenius androidsdl

             git clone git://github.com/lubomyr/bochs
             
             #build
             cd bochs/build/android
              ./build-all.sh  
              ls -l
              ndk-build



